export class Verifydone {
    constructor(firstName:string,
        lastName:string,
        email:string,
        dob:string,
        age:number,
        address:string,
        panNo:string,
        passportId:number,
        dateofApplication:string,
        gender:string,
        citizenId:number,
        applicationId:number,
        aadharNo:string,
        currenStatus:string,
        issueDate:string,
        ){}
        firstName!:string;
        lastName!:string;
        email!:string;
        dob!:string;
        age!:number;
        address!:string;
        panNo!:string;
        passportId!:number;
        dateofApplication!:string;
        gender!:string;
        citizenId!:number;
        applicationId!:number;
        aadharNo!:string;
        currentStatus!:string;
        issueDate!:string;
}
